### ISSUE TITLE
Feature request: Add a dark-on-light theme

### ISSUE THREAD

**Issue by jay** [mozilla/lightbeam#483]
It would be easier on my eyes to switch in and out if the colors were inverted. None of the bookmarklets I have work properly for altering the style of the lightbeam page. I came pretty close by making an svg filter to invert the colors but the grays come out too light and a much bigger problem is it's slowing things down noticeably.

Thanks

stylish invert style i'm using for lightbeam:

``` css
html {
  filter: url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\' version=\'1.1\'> <defs> <filter id=\'invert\' x=\'0%\' y=\'0%\' width=\'100%\' height=\'100%\' > <feColorMatrix type=\'matrix\' values=\'-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0\'/> <feComponentTransfer> <feFuncR type=\'gamma\' offset=\'0\' amplitude=\'1\' exponent=\'4.84\'/> <feFuncG type=\'gamma\' offset=\'0\' amplitude=\'1\' exponent=\'4.84\'/> <feFuncB type=\'gamma\' offset=\'0\' amplitude=\'1\' exponent=\'4.84\'/> </feComponentTransfer> </filter> </defs> </svg>#invert");
}
```
